# image will be published to ghcr.io/<user>/<name>
name: aurora-os
# description will be included in the image's metadata
description: My daily driver OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://download.docker.com/linux/fedora/docker-ce.repo
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
    install:
      - code
      - clamav-freshclam
      - clamd
      - clamtk
      # podman not working for vscode's docker in docker
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      # waydroid
      - wl-clipboard
      - virt-manager
      - edk2-ovmf
      - qemu

    remove:
      - input-remapper
      - tailscale
      - joystickwake
      - joycond
      - xdotool
      - xwiimote-ng
      - rom-properties-kf5
      - cockpit-networkmanager
      - cockpit-podman
      - cockpit-selinux
      - cockpit-system
      - cockpit-navigator
      - cockpit-storaged

  - type: python-pip
    install:
      - pyclip

  - type: default-flatpaks
    notify: true   # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      # - org.gnome.Loupe
      # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08).
      # Only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Multiple install of same flatpaks with different branches is not supported.
        - com.github.tchx84.Flatseal
        - com.mongodb.Compass
        - com.github.Bleuzen.FFaudioConverter
        - io.dbeaver.DBeaverCommunity
        - com.getpostman.Postman
        - com.sweethome3d.Sweethome3d
        - com.github.unrud.VideoDownloader
        - org.chromium.Chromium
        - one.ablaze.floorp
        - org.videolan.VLC
        - org.gimp.GIMP
        - org.kde.krita
        - org.kde.kate
        - org.kde.kompare
        - org.inkscape.Inkscape
        - org.blender.Blender
        - org.keepassxc.KeePassXC
        - org.kde.kdenlive
        - org.kde.okular
        - org.remmina.Remmina
        - com.makemkv.MakeMKV
        - org.qbittorrent.qBittorrent
        - org.apache.directory.studio
        - org.raspberrypi.rpi-imager
        - org.mozilla.Thunderbird
        - md.obsidian.Obsidian
        - it.mijorus.gearlever
      remove:
        - org.kde.haruna
        - com.github.marhkb.Pods

    # A flatpak repo can also be added without having to install flatpaks,
    # as long as one of the repo- fields is present
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub

  - type: script
    scripts:
      - breeze-fedora-workaround.sh
      - systemd-dx.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
